//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistribuJob.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mozilla/5.0 (compatible; DistribuJob; exoget.com; {0})")]
        public string WebUseragent {
            get {
                return ((string)(this["WebUseragent"]));
            }
            set {
                this["WebUseragent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public ushort Server_MaxConsecutiveTimeouts {
            get {
                return ((ushort)(this["Server_MaxConsecutiveTimeouts"]));
            }
            set {
                this["Server_MaxConsecutiveTimeouts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public ushort Server_MaxConsecutiveLookupFailures {
            get {
                return ((ushort)(this["Server_MaxConsecutiveLookupFailures"]));
            }
            set {
                this["Server_MaxConsecutiveLookupFailures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int Server_DefaultTimeout {
            get {
                return ((int)(this["Server_DefaultTimeout"]));
            }
            set {
                this["Server_DefaultTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public ushort Processor_Fetcher_Threads {
            get {
                return ((ushort)(this["Processor_Fetcher_Threads"]));
            }
            set {
                this["Processor_Fetcher_Threads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int MinImports {
            get {
                return ((int)(this["MinImports"]));
            }
            set {
                this["MinImports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int MaxImports {
            get {
                return ((int)(this["MaxImports"]));
            }
            set {
                this["MaxImports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MaxExports {
            get {
                return ((int)(this["MaxExports"]));
            }
            set {
                this["MaxExports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan MaxExportIdle {
            get {
                return ((global::System.TimeSpan)(this["MaxExportIdle"]));
            }
            set {
                this["MaxExportIdle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.00:00:00")]
        public global::System.TimeSpan Server_RobotsTxtExpire {
            get {
                return ((global::System.TimeSpan)(this["Server_RobotsTxtExpire"]));
            }
            set {
                this["Server_RobotsTxtExpire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public ushort Server_MaxConsecutiveUnsuccessfulRequests {
            get {
                return ((ushort)(this["Server_MaxConsecutiveUnsuccessfulRequests"]));
            }
            set {
                this["Server_MaxConsecutiveUnsuccessfulRequests"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte Server_MaxDelay {
            get {
                return ((byte)(this["Server_MaxDelay"]));
            }
            set {
                this["Server_MaxDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public ushort Processor_Fetcher_Slow_Threads {
            get {
                return ((ushort)(this["Processor_Fetcher_Slow_Threads"]));
            }
            set {
                this["Processor_Fetcher_Slow_Threads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:10")]
        public global::System.TimeSpan Processor_Fetcher_SlowTime {
            get {
                return ((global::System.TimeSpan)(this["Processor_Fetcher_SlowTime"]));
            }
            set {
                this["Processor_Fetcher_SlowTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public ushort Processor_Fetcher_MaxSlow {
            get {
                return ((ushort)(this["Processor_Fetcher_MaxSlow"]));
            }
            set {
                this["Processor_Fetcher_MaxSlow"] = value;
            }
        }
    }
}
